/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package provaa1_estoque.UI;

import provaa1_estoque.BLL.EstoqueBLL;

/**
 *
 * @author danilotavareslima
 */
public class FormPrincipal extends javax.swing.JFrame {

    EstoqueBLL bll = new EstoqueBLL();

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormPrincipal.class.getName());

    /**
     * Creates new form FormPrincipal
     */
    public FormPrincipal() {
        initComponents();
        configurarLayout();
        carregarTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblEstoque = new javax.swing.JTable();
        btnNovo = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        iconEstoque = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblEstoque.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Quantidade", "Valor Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblEstoque.setColumnSelectionAllowed(true);
        jScrollPane1.setViewportView(tblEstoque);
        tblEstoque.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        btnNovo.setText("Novo");
        btnNovo.addActionListener(this::btnNovoActionPerformed);
        getContentPane().add(btnNovo, java.awt.BorderLayout.PAGE_START);

        btnEditar.setText("Editar");
        btnEditar.addActionListener(this::btnEditarActionPerformed);
        getContentPane().add(btnEditar, java.awt.BorderLayout.PAGE_END);

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(this::btnExcluirActionPerformed);
        getContentPane().add(btnExcluir, java.awt.BorderLayout.LINE_END);

        iconEstoque.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconEstoque.setIcon(new javax.swing.ImageIcon(getClass().getResource("/provaa1_estoque/imagens/iconeestoque.jpeg"))); // NOI18N
        iconEstoque.setAlignmentX(0.5F);
        getContentPane().add(iconEstoque, java.awt.BorderLayout.LINE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed

        int linhaSelecionada = tblEstoque.getSelectedRow();
        if (linhaSelecionada == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Selecione um registro para excluir.");
            return;
        }
        int confirm = javax.swing.JOptionPane.showConfirmDialog(this, "Deseja excluir este registro?");
        if (confirm != javax.swing.JOptionPane.YES_OPTION) {
            return;
        }
        int id = (int) tblEstoque.getValueAt(linhaSelecionada, 0);
        try {
            bll.excluirEstoque(id);
            carregarTabela();
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Erro ao excluir: " + e.getMessage());
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed

        FormCadastro fc = new FormCadastro(this, true);
        fc.setVisible(true);
        carregarTabela();
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed

        int linhaSelecionada = tblEstoque.getSelectedRow();
        if (linhaSelecionada == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Selecione um registro para editar.");
            return;
        }
        int id = (int) tblEstoque.getValueAt(linhaSelecionada, 0);
        try {
            provaa1_estoque.DTO.EstoqueDTO estoque = bll.selecionarEstoquePorID(id);
            FormCadastro fc = new FormCadastro(this, true, estoque);
            fc.setVisible(true);
            carregarTabela();
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Erro: " + e.getMessage());
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    public void carregarTabela() {
        try {
            javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) tblEstoque.getModel();
            modelo.setRowCount(0);
            java.util.List lista = bll.selecionarListaEstoque();
            for (Object obj : lista) {
                provaa1_estoque.DTO.EstoqueDTO estoque = (provaa1_estoque.DTO.EstoqueDTO) obj;
                modelo.addRow(new Object[]{
                    estoque.getEstID(),
                    estoque.getEstQtd(),
                    estoque.getEstValorTotal()
                });
            }
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Erro ao carregar: " + e.getMessage());
        }
    }

    private void configurarLayout() {
        getContentPane().setLayout(new java.awt.BorderLayout(5, 5));

        iconEstoque.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        getContentPane().add(iconEstoque, java.awt.BorderLayout.NORTH);

        ((javax.swing.JComponent) getContentPane()).setBorder(
                javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 2)
        );

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        javax.swing.JPanel painelBotoes = new javax.swing.JPanel();
        painelBotoes.add(btnNovo);
        painelBotoes.add(btnEditar);
        painelBotoes.add(btnExcluir);
        getContentPane().add(painelBotoes, java.awt.BorderLayout.SOUTH);

        setSize(600, 450);
        setLocationRelativeTo(null);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnNovo;
    private javax.swing.JLabel iconEstoque;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblEstoque;
    // End of variables declaration//GEN-END:variables
}
